modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="stalkermod"
version="1.0.0"
displayName="Stalker Mod"
description='''The Whistler and Daddy in Red. They spot you from far away and chase you.'''

[[dependencies.stalkermod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.stalkermod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
